apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-svc2-svcacc
  namespace: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service2
  namespace: demo
spec:
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  selector:
    app: demo-service2
    version: "v1"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-service2
    app.kubernetes.io/part-of: demo
    app.kubernetes.io/version: v1
  name: demo-service2
  namespace: demo
spec:
  selector:
    matchLabels:
      app: demo-service2
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: demo-service2
        version: "v1"
    spec:
      containers:
        - name: demo-service2
          image: 'lhou/demo-service2:v2'
          ports:
            - containerPort: 8081
          env:
            - name: demo
              valueFrom:
                configMapKeyRef:
                  name: demo-service
                  key: demo-service-url
          resources:
            requests:
              cpu: 100m
      serviceAccountName: demo-svc2-svcacc
